site_name: Skeleton Project
site_description: __package-description__
site_author: __author-name__
repo_url: https://github.com/graze/skeleton-project
theme:
  name: 'material'
  custom_dir: docs/theme
  favicon: assets/images/favicon-192x192.png
  language: en
  include_sidebar: true
  palette:
    primary: 'cyan'
    accent: 'cyan'

nav:
  - Home: 'index.md'
  - 'External Services':
    - Travis: 'external_services/travis.md'
    - Scrutinizer: 'external_services/scrutinizer.md'
    - Packagist: 'external_services/packagist.md'
    - DockerHub: 'external_services/docker_hub.md'
    - GitHub: 'external_services/github.md'
    - 'GitHub Pages': 'external_services/github_pages.md'

markdown_extensions:
  - admonition:
  - markdown.extensions.tables:
  - pymdownx.magiclink:
  - pymdownx.tilde:
  - pymdownx.betterem:
  - pymdownx.superfences:
  - pymdownx.highlight:
      css_class: codehilite
      extend_pygments_lang:
        - name: php
          lang: php
          options:
            startinline: True
  - pymdownx.inlinehilite:
  - pymdownx.emoji:
  - pymdownx.escapeall:
      hardbreak: True
      nbsp: True
  - pymdownx.tasklist:
  - toc:
      permalink: true
